
# This file is automatically generated, you probably don't want to edit this

TestROCOptions <- if (requireNamespace('jmvcore')) R6::R6Class(
    "TestROCOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            dependentVar = NULL,
            classVar = NULL,
            subGroup = NULL,
            method = NULL,
            allObserved = NULL,
            specifyCutScore = NULL,
            metric = NULL,
            boot_runs = NULL,
            use_midpoint = NULL,
            break_ties = NULL,
            tol_metric = NULL,
            direction = NULL,
            plotROC = TRUE, ...) {

            super$initialize(
                package='TestROC',
                name='TestROC',
                requiresData=TRUE,
                ...)

            private$..dependentVar <- jmvcore::OptionVariable$new(
                "dependentVar",
                dependentVar)
            private$..classVar <- jmvcore::OptionVariable$new(
                "classVar",
                classVar)
            private$..subGroup <- jmvcore::OptionVariable$new(
                "subGroup",
                subGroup)
            private$..method <- jmvcore::OptionList$new(
                "method",
                method,
                options=list(
                    "maximize_metric",
                    "minimise_metric",
                    "maximize_loess_metric",
                    "minimize_loess_metric",
                    "maximize_spline_metric",
                    "minimize_spline_metric",
                    "maximize_boot_metric",
                    "minimize_boot_metric",
                    "oc_youden_kernel",
                    "oc_youden_normal",
                    "oc_manual"))
            private$..allObserved <- jmvcore::OptionBool$new(
                "allObserved",
                allObserved)
            private$..specifyCutScore <- jmvcore::OptionString$new(
                "specifyCutScore",
                specifyCutScore)
            private$..metric <- jmvcore::OptionList$new(
                "metric",
                metric,
                options=list(
                    "sum_sens_spec",
                    "accuracy",
                    "youden",
                    "sum_sens_spec",
                    "sum_ppv_npv",
                    "prod_sens_spec",
                    "prod_ppv_npv",
                    "cohens_kappa",
                    "abs_d_sens_spec",
                    "roc01",
                    "abs_d_ppv_npv",
                    "p_chisquared",
                    "odds_ratio",
                    "risk_ratio",
                    "misclassification_cost",
                    "total_utility",
                    "F1_score"))
            private$..boot_runs <- jmvcore::OptionNumber$new(
                "boot_runs",
                boot_runs)
            private$..use_midpoint <- jmvcore::OptionBool$new(
                "use_midpoint",
                use_midpoint)
            private$..break_ties <- jmvcore::OptionList$new(
                "break_ties",
                break_ties,
                options=list(
                    "c",
                    "mean",
                    "median"))
            private$..tol_metric <- jmvcore::OptionNumber$new(
                "tol_metric",
                tol_metric)
            private$..direction <- jmvcore::OptionList$new(
                "direction",
                direction,
                options=list(
                    ">=",
                    "<="))
            private$..plotROC <- jmvcore::OptionBool$new(
                "plotROC",
                plotROC,
                default=TRUE)

            self$.addOption(private$..dependentVar)
            self$.addOption(private$..classVar)
            self$.addOption(private$..subGroup)
            self$.addOption(private$..method)
            self$.addOption(private$..allObserved)
            self$.addOption(private$..specifyCutScore)
            self$.addOption(private$..metric)
            self$.addOption(private$..boot_runs)
            self$.addOption(private$..use_midpoint)
            self$.addOption(private$..break_ties)
            self$.addOption(private$..tol_metric)
            self$.addOption(private$..direction)
            self$.addOption(private$..plotROC)
        }),
    active = list(
        dependentVar = function() private$..dependentVar$value,
        classVar = function() private$..classVar$value,
        subGroup = function() private$..subGroup$value,
        method = function() private$..method$value,
        allObserved = function() private$..allObserved$value,
        specifyCutScore = function() private$..specifyCutScore$value,
        metric = function() private$..metric$value,
        boot_runs = function() private$..boot_runs$value,
        use_midpoint = function() private$..use_midpoint$value,
        break_ties = function() private$..break_ties$value,
        tol_metric = function() private$..tol_metric$value,
        direction = function() private$..direction$value,
        plotROC = function() private$..plotROC$value),
    private = list(
        ..dependentVar = NA,
        ..classVar = NA,
        ..subGroup = NA,
        ..method = NA,
        ..allObserved = NA,
        ..specifyCutScore = NA,
        ..metric = NA,
        ..boot_runs = NA,
        ..use_midpoint = NA,
        ..break_ties = NA,
        ..tol_metric = NA,
        ..direction = NA,
        ..plotROC = NA)
)

TestROCResults <- if (requireNamespace('jmvcore')) R6::R6Class(
    inherit = jmvcore::Group,
    active = list(
        debug = function() private$.items[["debug"]],
        resultsTable = function() private$.items[["resultsTable"]],
        sensSpecTable = function() private$.items[["sensSpecTable"]],
        plotROC = function() private$.items[["plotROC"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="TestROC")
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="debug"))
            self$add(jmvcore::Table$new(
                options=options,
                name="resultsTable",
                title="Results Table",
                rows=0,
                columns=list(
                    list(
                        `name`="scaleName", 
                        `title`="Scale", 
                        `type`="text"),
                    list(
                        `name`="cutpoint", 
                        `title`="Cutpoint", 
                        `type`="text"),
                    list(
                        `name`="sensitivity", 
                        `title`="Sensitivity (%)", 
                        `type`="text"),
                    list(
                        `name`="specificity", 
                        `title`="Specificity (%)", 
                        `type`="text"),
                    list(
                        `name`="ppv", 
                        `title`="PPV (%)", 
                        `type`="text"),
                    list(
                        `name`="npv", 
                        `title`="NPV (%)", 
                        `type`="number"),
                    list(
                        `name`="youden", 
                        `title`="Youden's index", 
                        `type`="number"),
                    list(
                        `name`="AUC", 
                        `title`="AUC", 
                        `type`="number"))))
            self$add(jmvcore::Html$new(
                options=options,
                name="sensSpecTable",
                title="Sensitivity & Specificity"))
            self$add(jmvcore::Image$new(
                options=options,
                name="plotROC",
                width=550,
                height=450,
                renderFun=".plotROC",
                visible="(plotROC)",
                requiresData=TRUE))}))

TestROCBase <- if (requireNamespace('jmvcore')) R6::R6Class(
    "TestROCBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = 'TestROC',
                name = 'TestROC',
                version = c(1,0,0),
                options = options,
                results = TestROCResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE)
        }))

#' TestROC
#'
#' 
#' @param data .
#' @param dependentVar .
#' @param classVar .
#' @param subGroup .
#' @param method .
#' @param allObserved .
#' @param specifyCutScore .
#' @param metric .
#' @param boot_runs .
#' @param use_midpoint .
#' @param break_ties .
#' @param tol_metric .
#' @param direction .
#' @param plotROC .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$debug} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$resultsTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$sensSpecTable} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$plotROC} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$resultsTable$asDF}
#'
#' \code{as.data.frame(results$resultsTable)}
#'
#' @export
TestROC <- function(
    data,
    dependentVar,
    classVar,
    subGroup,
    method,
    allObserved,
    specifyCutScore,
    metric,
    boot_runs,
    use_midpoint,
    break_ties,
    tol_metric,
    direction,
    plotROC = TRUE) {

    if ( ! requireNamespace('jmvcore'))
        stop('TestROC requires jmvcore to be installed (restart may be required)')

    if ( ! missing(dependentVar)) dependentVar <- jmvcore::resolveQuo(jmvcore::enquo(dependentVar))
    if ( ! missing(classVar)) classVar <- jmvcore::resolveQuo(jmvcore::enquo(classVar))
    if ( ! missing(subGroup)) subGroup <- jmvcore::resolveQuo(jmvcore::enquo(subGroup))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(dependentVar), dependentVar, NULL),
            `if`( ! missing(classVar), classVar, NULL),
            `if`( ! missing(subGroup), subGroup, NULL))


    options <- TestROCOptions$new(
        dependentVar = dependentVar,
        classVar = classVar,
        subGroup = subGroup,
        method = method,
        allObserved = allObserved,
        specifyCutScore = specifyCutScore,
        metric = metric,
        boot_runs = boot_runs,
        use_midpoint = use_midpoint,
        break_ties = break_ties,
        tol_metric = tol_metric,
        direction = direction,
        plotROC = plotROC)

    results <- TestROCResults$new(
        options = options)

    analysis <- TestROCClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}
