
# This file is automatically generated, you probably don't want to edit this

TestROCOptions <- if (requireNamespace('jmvcore')) R6::R6Class(
    "TestROCOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            dependentVar = NULL,
            classVar = NULL,
            subGroup = NULL,
            method = NULL,
            specifyCutScore = NULL,
            metric = NULL,
            boot_runs = NULL,
            use_midpoint = NULL,
            break_ties = NULL,
            tol_metric = NULL,
            ROC = NULL, ...) {

            super$initialize(
                package='TestROC',
                name='TestROC',
                requiresData=TRUE,
                ...)

            private$..dependentVar <- jmvcore::OptionVariable$new(
                "dependentVar",
                dependentVar)
            private$..classVar <- jmvcore::OptionVariable$new(
                "classVar",
                classVar)
            private$..subGroup <- jmvcore::OptionVariable$new(
                "subGroup",
                subGroup)
            private$..method <- jmvcore::OptionList$new(
                "method",
                method,
                options=list(
                    "optionA"))
            private$..specifyCutScore <- jmvcore::OptionNumber$new(
                "specifyCutScore",
                specifyCutScore)
            private$..metric <- jmvcore::OptionList$new(
                "metric",
                metric,
                options=list(
                    "optionA"))
            private$..boot_runs <- jmvcore::OptionNumber$new(
                "boot_runs",
                boot_runs)
            private$..use_midpoint <- jmvcore::OptionBool$new(
                "use_midpoint",
                use_midpoint)
            private$..break_ties <- jmvcore::OptionBool$new(
                "break_ties",
                break_ties)
            private$..tol_metric <- jmvcore::OptionNumber$new(
                "tol_metric",
                tol_metric)
            private$..ROC <- jmvcore::OptionBool$new(
                "ROC",
                ROC)

            self$.addOption(private$..dependentVar)
            self$.addOption(private$..classVar)
            self$.addOption(private$..subGroup)
            self$.addOption(private$..method)
            self$.addOption(private$..specifyCutScore)
            self$.addOption(private$..metric)
            self$.addOption(private$..boot_runs)
            self$.addOption(private$..use_midpoint)
            self$.addOption(private$..break_ties)
            self$.addOption(private$..tol_metric)
            self$.addOption(private$..ROC)
        }),
    active = list(
        dependentVar = function() private$..dependentVar$value,
        classVar = function() private$..classVar$value,
        subGroup = function() private$..subGroup$value,
        method = function() private$..method$value,
        specifyCutScore = function() private$..specifyCutScore$value,
        metric = function() private$..metric$value,
        boot_runs = function() private$..boot_runs$value,
        use_midpoint = function() private$..use_midpoint$value,
        break_ties = function() private$..break_ties$value,
        tol_metric = function() private$..tol_metric$value,
        ROC = function() private$..ROC$value),
    private = list(
        ..dependentVar = NA,
        ..classVar = NA,
        ..subGroup = NA,
        ..method = NA,
        ..specifyCutScore = NA,
        ..metric = NA,
        ..boot_runs = NA,
        ..use_midpoint = NA,
        ..break_ties = NA,
        ..tol_metric = NA,
        ..ROC = NA)
)

TestROCResults <- if (requireNamespace('jmvcore')) R6::R6Class(
    inherit = jmvcore::Group,
    active = list(
        text = function() private$.items[["text"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="TestROC")
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="text",
                title="TestROC"))}))

TestROCBase <- if (requireNamespace('jmvcore')) R6::R6Class(
    "TestROCBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = 'TestROC',
                name = 'TestROC',
                version = c(1,0,0),
                options = options,
                results = TestROCResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE)
        }))

#' TestROC
#'
#' 
#' @param data .
#' @param dependentVar .
#' @param classVar .
#' @param subGroup .
#' @param method .
#' @param specifyCutScore .
#' @param metric .
#' @param boot_runs .
#' @param use_midpoint .
#' @param break_ties .
#' @param tol_metric .
#' @param ROC .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$text} \tab \tab \tab \tab \tab a preformatted \cr
#' }
#'
#' @export
TestROC <- function(
    data,
    dependentVar,
    classVar,
    subGroup,
    method,
    specifyCutScore,
    metric,
    boot_runs,
    use_midpoint,
    break_ties,
    tol_metric,
    ROC) {

    if ( ! requireNamespace('jmvcore'))
        stop('TestROC requires jmvcore to be installed (restart may be required)')

    if ( ! missing(dependentVar)) dependentVar <- jmvcore::resolveQuo(jmvcore::enquo(dependentVar))
    if ( ! missing(classVar)) classVar <- jmvcore::resolveQuo(jmvcore::enquo(classVar))
    if ( ! missing(subGroup)) subGroup <- jmvcore::resolveQuo(jmvcore::enquo(subGroup))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(dependentVar), dependentVar, NULL),
            `if`( ! missing(classVar), classVar, NULL),
            `if`( ! missing(subGroup), subGroup, NULL))


    options <- TestROCOptions$new(
        dependentVar = dependentVar,
        classVar = classVar,
        subGroup = subGroup,
        method = method,
        specifyCutScore = specifyCutScore,
        metric = metric,
        boot_runs = boot_runs,
        use_midpoint = use_midpoint,
        break_ties = break_ties,
        tol_metric = tol_metric,
        ROC = ROC)

    results <- TestROCResults$new(
        options = options)

    analysis <- TestROCClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}
